# Generated by Django 5.1.1 on 2024-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='had_bye',
            field=models.BooleanField(default=False),
        ),
    ]
