# Generated by Django 5.1.1 on 2024-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_had_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairing',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
