# Generated by Django 5.1.1 on 2024-10-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_player_game_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_points',
        ),
    ]
