# Generated by Django 5.1.1 on 2024-10-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_player_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='was_bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='player1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='player2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='result',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='round',
            field=models.IntegerField(),
        ),
    ]
