# Generated by Django 5.1.1 on 2024-10-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_tournament_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_player1', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairings_as_player2', to='tournament.player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_of',
            field=models.IntegerField(choices=[(1, 'Best of 1'), (3, 'Best of 3'), (5, 'Best of 5')], default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pairing_method',
            field=models.CharField(choices=[('Swiss', 'Swiss'), ('Single Eliminations', 'Single Eliminations')], default='Swiss', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Constructed', 'Constructed'), ('Sealed Deck', 'Sealed Deck')], default='Draft', max_length=20),
        ),
    ]
