# Generated by Django 5.1.1 on 2024-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_pairing_player1_alter_pairing_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='game_win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='match_win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='opponents_game_win_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='opponents_match_win_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
