# Generated by Django 5.1.1 on 2024-10-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_player_game_points_player_game_win_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match_win_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opponents_game_win_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opponents_match_win_percentage',
        ),
    ]
