# Generated by Django 5.1.1 on 2024-10-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_player_match_win_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_win_percentage',
            new_name='gwp',
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
    ]
