# Generated by Django 5.1.1 on 2024-10-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_rename_game_win_percentage_player_gwp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='gwp',
            new_name='game_win_percentage',
        ),
    ]
