# Generated by Django 5.1.1 on 2024-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_rename_gwp_player_game_win_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AddField(
            model_name='player',
            name='games_drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
    ]
