# Generated by Django 5.1.1 on 2024-10-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_remove_player_game_points_remove_player_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_win_percentage',
        ),
    ]
