# Generated by Django 5.1.1 on 2024-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_remove_player_game_win_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_win_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
