# Generated by Django 5.1.1 on 2024-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_player_game_win_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opponents_match_win_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
